[package]
authors = ["Zengor <ialmeida@edu.unifor.br>"]
edition = "2018"
name = "list_to_anki"
version = "0.2.2"
[dependencies]
clap = "2.33.0"
rayon = "1.2.0"
reqwest = "0.9.20"
serde = { version="1.0.100", features = ["derive"] }
serde_json = "1.0.40"
